<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add new album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
//  $form->setAttribute('action', $this->url('album', array('action' => 'add')));
//  $form->prepare();

//  echo $this->form()->openTag($form);
//  echo $this->formHidden($form->get('id'));
//  echo $this->formRow($form->get('title'));
//  echo $this->formRow($form->get('artist'));
//  echo $this->formSubmit($form->get('submit'));
//  echo $this->form()->closeTag();

?>
<form role="form" action="<?php echo $this->url('album',array('action'=>'add'))?>" method="post">
<div class="col-md-6">
<div class="form-group">
	<label for="title">Title</label>
	<input type="title" class="form-control" id="title" palceholder="enter title" name="title">
</div>
</div>
<div class="col-md-6">
<div class="form-group">
	<label for="artist">artist</label>
	<input type="text" class="form-control" id="artist" palceholder="enter artist"  name="artist">
</div>
</div>

<div class="form-group">
<button type="submit" class="btn btn-default">Submit</button>
</div>

</form>